name: ROS 2 CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS 2 Iron
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: iron

      - name: Build and Test ROS 2 workspace
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: iron
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              }
            }
